-- 20260831_001_create_login_schema.sql
-- 대상 DB: s-erp_central (PostgreSQL)
-- 목적: 로그인/JWT 연동에 필요한 6개 테이블 신규 생성
-- 참고: 동일 서버의 haccp_cloud_central DB 스키마 구조를 기준으로 작성

CREATE TABLE IF NOT EXISTS tb_tenant (
  tenant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_code varchar(50) NOT NULL UNIQUE,
  tenant_nm varchar(200) NOT NULL,
  admin_email varchar(100) NOT NULL UNIQUE,
  admin_name varchar(100),
  business_registration_number varchar(12),
  corporate_number varchar(14),
  business_type varchar(200),
  business_category varchar(200),
  registration_date date,
  logo_image text,
  onboarding_status varchar(50) NOT NULL DEFAULT 'EMAIL_QUEUED',
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  created_by bigint
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_tenant_business_registration_number_active
  ON tb_tenant (business_registration_number)
  WHERE business_registration_number IS NOT NULL AND use_at = 'Y';
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_tenant_corporate_number_active
  ON tb_tenant (corporate_number)
  WHERE corporate_number IS NOT NULL AND use_at = 'Y';

CREATE TABLE IF NOT EXISTS tb_department (
  department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  department_nm varchar(100) NOT NULL,
  parent_department_id bigint REFERENCES tb_department(department_id) ON DELETE SET NULL,
  sort_order integer NOT NULL DEFAULT 0,
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tenant_department ON tb_department (tenant_id);
CREATE INDEX IF NOT EXISTS idx_parent_department ON tb_department (parent_department_id);

CREATE TABLE IF NOT EXISTS tb_role (
  role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  role_code varchar(50) NOT NULL,
  role_nm varchar(100) NOT NULL,
  role_dc varchar(500),
  use_at char(1) NOT NULL DEFAULT 'Y',
  is_system_role char(1) NOT NULL DEFAULT 'N',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, role_code)
);
CREATE INDEX IF NOT EXISTS idx_tenant_role ON tb_role (tenant_id);

CREATE TABLE IF NOT EXISTS tb_login_account (
  login_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  login_code varchar(100) NOT NULL,
  password_hash varchar(255) NOT NULL,
  profile_image text,
  stamp_image text,
  login_attempt_count integer DEFAULT 0,
  locked_at timestamp,
  password_changed_at timestamp,
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, login_code)
);
CREATE INDEX IF NOT EXISTS idx_tenant_login_account ON tb_login_account (tenant_id);
CREATE INDEX IF NOT EXISTS idx_login_code ON tb_login_account (login_code);

CREATE TABLE IF NOT EXISTS tb_login_account_role (
  login_account_role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_id bigint NOT NULL REFERENCES tb_login_account(login_id) ON DELETE CASCADE,
  role_id bigint NOT NULL REFERENCES tb_role(role_id) ON DELETE CASCADE,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (login_id, role_id)
);

CREATE TABLE IF NOT EXISTS tb_user (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  login_id bigint REFERENCES tb_login_account(login_id) ON DELETE SET NULL,
  user_nm varchar(100) NOT NULL,
  email_addr varchar(100),
  department_id bigint REFERENCES tb_department(department_id) ON DELETE SET NULL,
  mobile_no varchar(20),
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, email_addr)
);
CREATE INDEX IF NOT EXISTS idx_tenant_user ON tb_user (tenant_id);
CREATE INDEX IF NOT EXISTS idx_user_department ON tb_user (department_id);
CREATE INDEX IF NOT EXISTS idx_user_login_id ON tb_user (login_id);
