-- 20260831_003_create_module_menu_schema.sql
-- 대상 DB: s-erp_central (PostgreSQL)
-- 목적: 모듈/메뉴 관리 기능(작업지시서 20260831_002)을 위한 2개 테이블 신규 생성

CREATE TABLE IF NOT EXISTS tb_module (
  module_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  module_code varchar(50) NOT NULL,
  module_nm varchar(100) NOT NULL,
  icon_nm varchar(50),
  module_url varchar(200),
  sort_order integer NOT NULL DEFAULT 0,
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, module_code)
);
CREATE INDEX IF NOT EXISTS idx_tenant_module ON tb_module (tenant_id);

CREATE TABLE IF NOT EXISTS tb_menu (
  menu_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  module_id bigint NOT NULL REFERENCES tb_module(module_id) ON DELETE CASCADE,
  parent_menu_id bigint REFERENCES tb_menu(menu_id) ON DELETE CASCADE,
  menu_code varchar(50) NOT NULL,
  menu_nm varchar(100) NOT NULL,
  menu_url varchar(200),
  icon_nm varchar(50),
  sort_order integer NOT NULL DEFAULT 0,
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, menu_code)
);
CREATE INDEX IF NOT EXISTS idx_tenant_menu ON tb_menu (tenant_id);
CREATE INDEX IF NOT EXISTS idx_module_menu ON tb_menu (module_id);
CREATE INDEX IF NOT EXISTS idx_parent_menu ON tb_menu (parent_menu_id);
