-- 20260909_001_create_warehouse_schema.sql
-- 대상 DB: s-erp_central (PostgreSQL)
-- 목적: 창고(warehouse) 관리 기능을 위한 테이블 신규 생성

CREATE TABLE IF NOT EXISTS tb_warehouse (
  warehouse_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id bigint NOT NULL REFERENCES tb_tenant(tenant_id) ON DELETE CASCADE,
  warehouse_nm varchar(100) NOT NULL,
  use_at char(1) NOT NULL DEFAULT 'Y',
  created_by bigint,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_by bigint,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, warehouse_nm)
);
CREATE INDEX IF NOT EXISTS idx_tenant_warehouse ON tb_warehouse (tenant_id);
